# Generated by Django 4.2.20 on 2025-08-09 18:49

import circuitMoto.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('DEJA_ASSURE', 'Déjà assuré'), ('DEMANDE_OFFRE', 'Souhaite une offre')], default='DEJA_ASSURE', max_length=16, verbose_name='Type')),
                ('compagnie', models.CharField(blank=True, max_length=120, verbose_name='Compagnie')),
                ('numero_police', models.CharField(blank=True, max_length=120, verbose_name='N° de police')),
                ('valide_du', models.DateField(blank=True, null=True, verbose_name='Valable du')),
                ('valide_au', models.DateField(blank=True, null=True, verbose_name='Valable au')),
            ],
            options={
                'verbose_name': 'Assurance',
                'verbose_name_plural': 'Assurances',
            },
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=160, verbose_name='Nom du circuit')),
                ('code', models.SlugField(help_text='Ex : corse-2025-06', max_length=80, unique=True, verbose_name='Code')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('infos_rdv', models.TextField(blank=True, verbose_name='Infos de rendez-vous')),
                ('capacite', models.PositiveIntegerField(default=0, verbose_name='Capacité (participants)')),
                ('devise', models.CharField(choices=[('XOF', 'Franc CFA (XOF)'), ('EUR', 'Euro (EUR)')], default='XOF', max_length=3, verbose_name='Devise')),
                ('prix_pilote_unitaire', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix pilote (unitaire)')),
                ('prix_passager_unitaire', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix passager (unitaire)')),
                ('delai_option_jours', models.PositiveIntegerField(default=10, verbose_name='Durée de validité d’option (jours)')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=16, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Circuit',
                'verbose_name_plural': 'Circuits',
                'ordering': ['-date_debut', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ContactUrgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('lien_parente', models.CharField(blank=True, max_length=80, verbose_name='Lien de parenté')),
                ('telephone', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide.', regex='^[0-9+\\s\\-().]{6,20}$')], verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Contact d’urgence',
                'verbose_name_plural': 'Contacts d’urgence',
            },
        ),
        migrations.CreateModel(
            name='DechargeSignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('version_texte', models.CharField(help_text='Ex : CGV-2025-01', max_length=64, verbose_name='Version du texte')),
                ('nom_signataire', models.CharField(max_length=160, verbose_name='Nom du signataire')),
                ('email_signataire', models.EmailField(max_length=254, verbose_name='Email du signataire')),
                ('signee_le', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Signée le')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('otp_4_derniers', models.CharField(blank=True, max_length=4, verbose_name='OTP (4 derniers)')),
                ('preuve_pdf', models.FileField(blank=True, upload_to=circuitMoto.models.televersement_vers_decharge_pdf, verbose_name='Preuve PDF')),
            ],
            options={
                'verbose_name': 'Décharge signée',
                'verbose_name_plural': 'Décharges signées',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('type_document', models.CharField(choices=[('CNI', 'Carte d’identité'), ('PERMIS_CONDUIRE', 'Permis de conduire'), ('CARTE_GRISE', 'Carte grise / immatriculation'), ('ATTEST_ASSURANCE', 'Attestation d’assurance'), ('CERTIF_MEDICAL', 'Certificat médical'), ('AUTRE', 'Autre')], max_length=32, verbose_name='Type de document')),
                ('fichier', models.FileField(upload_to=circuitMoto.models.televersement_vers_document, verbose_name='Fichier')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=16, verbose_name='Statut')),
                ('verifie_le', models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='InfosMedicales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=4, verbose_name='Groupe sanguin')),
                ('hta', models.BooleanField(default=False, verbose_name='Hypertension artérielle')),
                ('asthme', models.BooleanField(default=False, verbose_name='Asthme')),
                ('epilepsie', models.BooleanField(default=False, verbose_name='Épilepsie')),
                ('problemes_peau', models.BooleanField(default=False, verbose_name='Eczéma/irritations')),
                ('vertiges', models.BooleanField(default=False, verbose_name='Vertiges')),
                ('notes', models.TextField(blank=True, verbose_name='Notes médicales')),
            ],
            options={
                'verbose_name': 'Infos médicales',
                'verbose_name_plural': 'Infos médicales',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('id_public', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identifiant public')),
                ('devise', models.CharField(choices=[('XOF', 'Franc CFA (XOF)'), ('EUR', 'Euro (EUR)')], max_length=3, verbose_name='Devise')),
                ('prix_pilote_unitaire', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix pilote figé')),
                ('prix_passager_unitaire', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix passager figé')),
                ('statut', models.CharField(choices=[('OPTION', 'Option posée'), ('VALIDE', 'Validée'), ('ANNULEE', 'Annulée'), ('TERMINEE', 'Terminée')], default='OPTION', max_length=16, verbose_name='Statut')),
                ('date_option', models.DateField(default=circuitMoto.models.aujourdhui, verbose_name='Date d’option')),
                ('option_expire_le', models.DateField(blank=True, null=True, verbose_name='Option expire le')),
                ('verrouillee_le', models.DateTimeField(blank=True, help_text='Fige les tarifs/quantités', null=True, verbose_name='Verrouillée le')),
                ('sous_total_fige', models.PositiveIntegerField(default=0, verbose_name='Sous-total figé')),
                ('total_fige', models.PositiveIntegerField(default=0, verbose_name='Total figé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=80, verbose_name='Action')),
                ('donnees', models.JSONField(blank=True, default=dict, verbose_name='Données')),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audit',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='JournalRappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('type_rappel', models.CharField(choices=[('EXPIRATION_OPTION', 'Expiration d’option'), ('RELANCE_ACOMPTE1', 'Relance Acompte 1'), ('RELANCE_ACOMPTE2', 'Relance Acompte 2'), ('RELANCE_SOLDE', 'Relance Solde'), ('DOCUMENT_MANQUANT', 'Document manquant'), ('GENERIQUE', 'Générique')], max_length=32, verbose_name='Type')),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=16, verbose_name='Canal')),
                ('destinataire', models.CharField(max_length=160, verbose_name='Destinataire')),
                ('envoye_le', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Envoyé le')),
                ('extrait_message', models.CharField(blank=True, max_length=255, verbose_name='Aperçu du message')),
            ],
            options={
                'verbose_name': 'Journal de rappel',
                'verbose_name_plural': 'Journaux de rappel',
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('marque', models.CharField(max_length=80, verbose_name='Marque')),
                ('modele', models.CharField(blank=True, max_length=80, verbose_name='Modèle')),
                ('immatriculation', models.CharField(blank=True, max_length=32, verbose_name='Immatriculation')),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos',
            },
        ),
        migrations.CreateModel(
            name='OptionCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, verbose_name='Code option')),
                ('intitule', models.CharField(max_length=160, verbose_name='Intitulé')),
                ('categorie', models.CharField(choices=[('HEBERGEMENT', 'Hébergement (chambre single, etc.)'), ('CABINE', 'Cabine ferry'), ('NUIT_ETAPE', 'Nuit d’étape'), ('AUTRE', 'Autre option')], max_length=16, verbose_name='Catégorie')),
                ('prix_unitaire', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire')),
                ('facture_par_personne', models.BooleanField(default=False, verbose_name='Facturé par personne')),
                ('quantite_variable', models.BooleanField(default=False, verbose_name='Quantité variable')),
                ('quantite_min', models.PositiveIntegerField(default=0, verbose_name='Quantité min.')),
                ('quantite_max', models.PositiveIntegerField(default=0, verbose_name='Quantité max (0 = illimitée)')),
            ],
            options={
                'verbose_name': 'Option de circuit',
                'verbose_name_plural': 'Options de circuit',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(choices=[('ACOMPTE1', 'Acompte 1'), ('ACOMPTE2', 'Acompte 2'), ('SOLDE', 'Solde'), ('AUTRE', 'Autre')], default='AUTRE', max_length=16, verbose_name='Libellé')),
                ('echeance_le', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('montant_du', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant attendu')),
                ('montant_encaisse', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant encaissé')),
                ('encaisse_le', models.DateField(blank=True, null=True, verbose_name='Payé le')),
                ('methode', models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('MOBILE_MONEY', 'Mobile Money')], max_length=16, verbose_name='Méthode')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Référence (bordereau, virement…)')),
                ('statut', models.CharField(choices=[('A_PAYER', 'À payer'), ('PARTIEL', 'Partiel'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé')], default='A_PAYER', max_length=16, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Paiement (hors système)',
                'verbose_name_plural': 'Paiements (hors système)',
            },
        ),
        migrations.CreateModel(
            name='SelectionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('quantite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('prix_unitaire_fige', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire figé')),
                ('pour_passager', models.BooleanField(default=False, help_text='Si facturé par personne, préciser pilote/passager.', verbose_name='Pour le passager')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections_options', to='circuitMoto.inscription')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='circuitMoto.optioncircuit')),
            ],
            options={
                'verbose_name': 'Sélection d’option',
                'verbose_name_plural': 'Sélections d’options',
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('prenom', models.CharField(max_length=80, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=80, verbose_name='Nom')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide.', regex='^[0-9+\\s\\-().]{6,20}$')], verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('code_postal', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('localite', models.CharField(blank=True, max_length=80, verbose_name='Localité')),
                ('pays', models.CharField(blank=True, max_length=80, verbose_name='Pays')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('numero_carte_identite', models.CharField(blank=True, max_length=64, verbose_name='N° carte d’identité')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
                'indexes': [models.Index(fields=['nom', 'prenom'], name='circuitMoto_nom_9cda0c_idx'), models.Index(fields=['email'], name='circuitMoto_email_5eadf3_idx'), models.Index(fields=['telephone'], name='circuitMoto_telepho_789041_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='personne',
            constraint=models.UniqueConstraint(fields=('email', 'telephone'), name='uniq_personne_email_tel'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='circuitMoto.inscription'),
        ),
        migrations.AddField(
            model_name='optioncircuit',
            name='circuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='circuitMoto.circuit'),
        ),
        migrations.AddField(
            model_name='moto',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motos', to='circuitMoto.personne'),
        ),
        migrations.AddField(
            model_name='journalrappel',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux_rappel', to='circuitMoto.inscription'),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='acteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journaux_audit', to='circuitMoto.inscription'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='circuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='circuitMoto.circuit'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscription',
            name='passager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_passager', to='circuitMoto.personne'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='pilote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_pilote', to='circuitMoto.personne'),
        ),
        migrations.AddField(
            model_name='infosmedicales',
            name='personne',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infos_medicales', to='circuitMoto.personne'),
        ),
        migrations.AddField(
            model_name='document',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='circuitMoto.inscription'),
        ),
        migrations.AddField(
            model_name='document',
            name='verifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_verifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dechargesignee',
            name='inscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decharge', to='circuitMoto.inscription'),
        ),
        migrations.AddField(
            model_name='contacturgence',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_urgence', to='circuitMoto.personne'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='inscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assurance', to='circuitMoto.inscription'),
        ),
        migrations.AddConstraint(
            model_name='selectionoption',
            constraint=models.UniqueConstraint(fields=('inscription', 'option', 'pour_passager'), name='uniq_option_par_inscription_passager'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['libelle'], name='circuitMoto_libelle_acdb6c_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut'], name='circuitMoto_statut_e76232_idx'),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.UniqueConstraint(fields=('inscription', 'libelle'), name='uniq_libelle_par_inscription'),
        ),
        migrations.AddConstraint(
            model_name='optioncircuit',
            constraint=models.UniqueConstraint(fields=('circuit', 'code'), name='uniq_option_code_par_circuit'),
        ),
        migrations.AddIndex(
            model_name='journalrappel',
            index=models.Index(fields=['type_rappel', 'canal', 'envoye_le'], name='circuitMoto_type_ra_ac91cc_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['statut'], name='circuitMoto_statut_35d290_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['circuit', 'statut'], name='circuitMoto_circuit_997b20_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('circuit', 'pilote'), name='uniq_pilote_par_circuit'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['type_document', 'statut'], name='circuitMoto_type_do_e57152_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('inscription', 'type_document'), name='uniq_type_document_par_inscription'),
        ),
    ]
