# Generated by Django 5.1.5 on 2025-08-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='dechargesignee',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature électronique (PNG)'),
        ),
    ]
