# Generated by Django 4.2.23 on 2025-08-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dechargesignee',
            name='otp_4_derniers',
        ),
        migrations.AddField(
            model_name='dechargesignee',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature électronique (PNG)'),
        ),
    ]
