# Generated by Django 4.2.23 on 2025-08-16 20:21

import circuitMoto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0003_remove_dechargesignee_otp_4_derniers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dechargesignee',
            name='preuve_pdf',
            field=models.FileField(blank=True, max_length=500, upload_to=circuitMoto.models.televersement_vers_decharge_pdf, verbose_name='Preuve PDF'),
        ),
        migrations.AlterField(
            model_name='dechargesignee',
            name='signature_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='signatures/', verbose_name='Signature électronique (PNG)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(max_length=500, upload_to=circuitMoto.models.televersement_vers_document, verbose_name='Fichier'),
        ),
    ]
