# Generated by Django 5.1.5 on 2025-08-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0003_dechargesignee_signature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dechargesignee',
            name='otp_4_derniers',
        ),
    ]
