# Generated by Django 4.2.23 on 2025-08-24 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0004_alter_dechargesignee_preuve_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurance',
            name='telephone_urgence',
            field=models.CharField(blank=True, default='', max_length=32, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide.', regex='^[0-9+\\s\\-().]{6,20}$')], verbose_name='N° d’urgence (assureur)'),
        ),
    ]
