# Generated by Django 5.1.5 on 2025-08-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0007_accountflags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePrefs',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('emails_pause_all', models.BooleanField(default=False)),
                ('emails_pause_pilote', models.BooleanField(default=False)),
                ('emails_pause_passager', models.BooleanField(default=False)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
