# Generated by Django 4.2.23 on 2025-11-08 21:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0008_circuit_description_en_circuit_description_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('prenom', models.CharField(max_length=80, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=80, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide.', regex='^[0-9+\\s\\-().]{6,20}$')], verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('interesse_circuit', models.BooleanField(default=False, verbose_name='Intéressé par un circuit ?')),
                ('statut_circuit', models.CharField(blank=True, choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié'), ('ARCHIVE', 'Archivé')], max_length=16, verbose_name='Statut du circuit')),
                ('type_demande', models.CharField(choices=[('INFO', 'Demande d’information'), ('RECLAMATION', 'Réclamation'), ('DEVIS', 'Demande de devis'), ('AUTRE', 'Autre')], default='INFO', max_length=16, verbose_name='Type de demande')),
                ('message', models.TextField(verbose_name='Votre message')),
                ('consent', models.BooleanField(default=False, verbose_name='J’accepte d’être contacté')),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AlterModelOptions(
            name='optioncircuit',
            options={'ordering': ('cree_le', 'id'), 'verbose_name': 'Option de circuit', 'verbose_name_plural': 'Options de circuit'},
        ),
        migrations.RemoveConstraint(
            model_name='optioncircuit',
            name='uniq_option_code_par_circuit',
        ),
        migrations.AddField(
            model_name='optioncircuit',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif (disponible à la vente)'),
        ),
        migrations.AddField(
            model_name='optioncircuit',
            name='archive_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archivé le'),
        ),
        migrations.AddConstraint(
            model_name='optioncircuit',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('circuit', 'code'), name='uniq_option_code_par_circuit_actives'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='circuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='circuitMoto.circuit'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['cree_le'], name='circuitMoto_cree_le_236364_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['statut_circuit'], name='circuitMoto_statut__c556f2_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['traite'], name='circuitMoto_traite_9ce6e4_idx'),
        ),
    ]
