# Generated by Django 4.2.23 on 2025-10-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0009_passwordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='nationalite',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nationalité'),
        ),
    ]
