# Generated by Django 4.2.23 on 2025-10-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0010_personne_nationalite'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='acompte1_par_personne',
            field=models.PositiveIntegerField(default=250, help_text='Montant fixe par personne, dans la devise du circuit.', verbose_name='Acompte 1 (par personne)'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='acompte2_par_personne',
            field=models.PositiveIntegerField(default=250, help_text='Montant fixe par personne, dans la devise du circuit.', verbose_name='Acompte 2 (par personne)'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='delai_acompte2_jours',
            field=models.PositiveIntegerField(default=60, help_text='Ex: 60 pour J-60.', verbose_name='Acompte 2 : J-jours avant départ'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='delai_solde_jours',
            field=models.PositiveIntegerField(default=30, help_text='Ex: 30 pour J-30.', verbose_name='Solde : J-jours avant départ'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='echeancier_texte',
            field=models.TextField(blank=True, verbose_name='Échéancier (texte libre)'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='kilometrages',
            field=models.TextField(blank=True, verbose_name='Kilométrages indicatifs'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='prix_comprend',
            field=models.TextField(blank=True, verbose_name='Le prix comprend'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='prix_ne_comprend_pas',
            field=models.TextField(blank=True, verbose_name='Le prix ne comprend pas'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='programme',
            field=models.TextField(blank=True, verbose_name='Programme (jour par jour)'),
        ),
        migrations.AddField(
            model_name='optioncircuit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
