# Generated by Django 4.2.23 on 2026-02-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0010_circuit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='email_checklist',
            field=models.TextField(blank=True, help_text='Une ligne = un item. Si vide, la checklist par défaut est utilisée.', verbose_name='Email - Checklist (override)'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='email_organisation',
            field=models.TextField(blank=True, help_text='Si vide, le texte par défaut est utilisé.', verbose_name='Email - Organisation du circuit (override)'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='email_rdv',
            field=models.TextField(blank=True, help_text='Si vide, le texte par défaut est utilisé. Tu peux mettre du texte multi-lignes.', verbose_name='Email - RDV / Logistique (override)'),
        ),
    ]
