# Generated by Django 4.2.23 on 2026-03-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0011_circuit_email_checklist_circuit_email_organisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Clé de session')),
                ('path', models.CharField(blank=True, default='/', max_length=255, verbose_name='Page visitée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visiteur du site',
                'verbose_name_plural': 'Visiteurs du site',
                'indexes': [models.Index(fields=['created_at'], name='circuitMoto_created_0bf016_idx'), models.Index(fields=['ip'], name='circuitMoto_ip_657f8a_idx'), models.Index(fields=['session_key'], name='circuitMoto_session_f036fb_idx')],
            },
        ),
    ]
