# Generated by Django 4.2.23 on 2025-10-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0011_circuit_acompte1_par_personne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='echeancier_texte_en',
            field=models.TextField(blank=True, null=True, verbose_name='Échéancier (texte libre)'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='echeancier_texte_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Échéancier (texte libre)'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='infos_rdv_en',
            field=models.TextField(blank=True, null=True, verbose_name='Infos de rendez-vous'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='infos_rdv_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Infos de rendez-vous'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='kilometrages_en',
            field=models.TextField(blank=True, null=True, verbose_name='Kilométrages indicatifs'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='kilometrages_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Kilométrages indicatifs'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='nom_en',
            field=models.CharField(max_length=160, null=True, verbose_name='Nom du circuit'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='nom_fr',
            field=models.CharField(max_length=160, null=True, verbose_name='Nom du circuit'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='prix_comprend_en',
            field=models.TextField(blank=True, null=True, verbose_name='Le prix comprend'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='prix_comprend_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Le prix comprend'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='prix_ne_comprend_pas_en',
            field=models.TextField(blank=True, null=True, verbose_name='Le prix ne comprend pas'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='prix_ne_comprend_pas_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Le prix ne comprend pas'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='programme_en',
            field=models.TextField(blank=True, null=True, verbose_name='Programme (jour par jour)'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='programme_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Programme (jour par jour)'),
        ),
        migrations.AddField(
            model_name='optioncircuit',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='optioncircuit',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='optioncircuit',
            name='intitule_en',
            field=models.CharField(max_length=160, null=True, verbose_name='Intitulé'),
        ),
        migrations.AddField(
            model_name='optioncircuit',
            name='intitule_fr',
            field=models.CharField(max_length=160, null=True, verbose_name='Intitulé'),
        ),
    ]
