# Generated by Django 4.2.23 on 2026-03-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0012_sitevisitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='montant_options_ajoutees',
            field=models.PositiveIntegerField(default=0, verbose_name='Montant options ajoutées après modification'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='paiement_options_recu',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
