# Generated by Django 4.2.23 on 2025-10-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0012_circuit_description_en_circuit_description_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='infos_paiement',
            field=models.TextField(blank=True, help_text='Texte libre : coordonnées bancaires, référence, CGV, barème annulation, etc.', verbose_name='Infos paiement (virement/CGV)'),
        ),
    ]
