# Generated by Django 4.2.23 on 2026-03-22 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0013_inscription_montant_options_ajoutees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaladeJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('date_affichage', models.CharField(blank=True, help_text='Ex: 9 et 10/5. Si vide, on affiche automatiquement la date.', max_length=80, verbose_name='Date affichée')),
                ('titre', models.CharField(max_length=220, verbose_name='Titre / circuit')),
                ('guide', models.CharField(blank=True, default='libre', max_length=120, verbose_name='Guide')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Balade 1 jour',
                'verbose_name_plural': 'Balades 1 jour',
                'ordering': ['date_debut', 'ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='DemandeProgrammeBalade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('prenom', models.CharField(max_length=80, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=80, verbose_name='Nom')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide.', regex='^[0-9+\\s\\-().]{6,20}$')], verbose_name='Téléphone')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('traite', models.BooleanField(db_index=True, default=False, verbose_name='Traité')),
                ('source', models.CharField(blank=True, default='page_balades_1_jour', max_length=120, verbose_name='Source')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User agent')),
                ('balades', models.ManyToManyField(related_name='demandes_programme', to='circuitMoto.baladejour', verbose_name='Balades sélectionnées')),
            ],
            options={
                'verbose_name': 'Demande programme balade',
                'verbose_name_plural': 'Demandes programme balades',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddIndex(
            model_name='baladejour',
            index=models.Index(fields=['actif', 'date_debut'], name='circuitMoto_actif_5b09b8_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeprogrammebalade',
            index=models.Index(fields=['email', 'cree_le'], name='circuitMoto_email_0c182d_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeprogrammebalade',
            index=models.Index(fields=['traite', 'cree_le'], name='circuitMoto_traite_5e0c90_idx'),
        ),
    ]
