# 0015_alter_optioncircuit_options_and_more.py
# Generated by Django 4.2.23 on 2025-11-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0014_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optioncircuit',
            options={'ordering': ('cree_le', 'id'), 'verbose_name': 'Option de circuit', 'verbose_name_plural': 'Options de circuit'},
        ),
        migrations.RemoveConstraint(
            model_name='optioncircuit',
            name='uniq_option_code_par_circuit',
        ),
        migrations.AddField(
            model_name='optioncircuit',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif (disponible à la vente)'),
        ),
        migrations.AddField(
            model_name='optioncircuit',
            name='archive_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archivé le'),
        ),
        migrations.AddConstraint(
            model_name='optioncircuit',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('circuit', 'code'), name='uniq_option_code_par_circuit_actives'),
        ),
    ]
