# Generated by Django 4.2.23 on 2026-03-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0014_baladejour_demandeprogrammebalade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baladejour',
            name='code_lien',
            field=models.CharField(blank=True, choices=[('', 'Pas de sous-lien'), ('A', 'A — Moto Zenith Huy'), ('B', 'B — Zone Rouge'), ('C', 'C — Ducati Sambreville'), ('D', 'D — JL Selection Neufchateau'), ('E', 'E — Moto Casu Mons'), ('F', 'F — Harley Liège'), ('G', 'G — XM Moto')], db_index=True, default='', max_length=1, verbose_name='Code sous-lien'),
        ),
        migrations.AddIndex(
            model_name='baladejour',
            index=models.Index(fields=['code_lien', 'actif', 'date_debut'], name='circuitMoto_code_li_44c64c_idx'),
        ),
    ]
