# Generated by Django 4.2.23 on 2026-03-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0015_baladejour_code_lien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baladejour',
            name='slug_lien',
            field=models.SlugField(blank=True, default='', help_text='Ex: zone-rouge ou moto-zenith-huy-namur-le-condroz', max_length=180, verbose_name='Slug du sous-lien'),
        ),
    ]
