# Generated by Django 4.2.23 on 2026-02-06 11:46

import circuitMoto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0015_alter_optioncircuit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='image',
            field=models.ImageField(blank=True, help_text='JPG/PNG/WebP conseillé. Champ optionnel.', null=True, upload_to=circuitMoto.models.circuit_image_upload_to, verbose_name='Image (optionnelle)'),
        ),
    ]
