# Generated by Django 4.2.23 on 2026-05-29 15:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0016_baladejour_slug_lien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme2027Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=180, verbose_name='Circuit')),
                ('slug', models.SlugField(max_length=190, unique=True, verbose_name='Slug')),
                ('mois', models.CharField(max_length=80, verbose_name='Mois / periode')),
                ('duree', models.CharField(max_length=80, verbose_name='Duree')),
                ('formule', models.CharField(blank=True, max_length=180, verbose_name='Formule')),
                ('categorie', models.CharField(choices=[('GRAND_VOYAGE', 'Grand voyage'), ('EUROPE', 'Europe'), ('FRANCE_BELGIQUE', 'France / Belgique'), ('RAID', 'Raid / aventure')], db_index=True, default='EUROPE', max_length=24, verbose_name='Categorie')),
                ('lien_reference', models.URLField(blank=True, max_length=700, verbose_name='Lien reference')),
                ('note', models.TextField(blank=True, verbose_name='Note interne')),
                ('ordre', models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Circuit pre programme 2027',
                'verbose_name_plural': 'Circuits pre programme 2027',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Programme2027Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('prenom', models.CharField(max_length=80, verbose_name='Prenom')),
                ('nom', models.CharField(max_length=80, verbose_name='Nom')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide.', regex='^[0-9+\\s\\-().]{6,20}$')], verbose_name='Telephone')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('code_postal', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('localite', models.CharField(blank=True, max_length=80, verbose_name='Localite')),
                ('pays', models.CharField(blank=True, max_length=80, verbose_name='Pays')),
                ('profil', models.CharField(blank=True, max_length=120, verbose_name='Profil voyageur')),
                ('vehicule', models.CharField(blank=True, max_length=160, verbose_name='Vehicule / preference')),
                ('participants_previsionnels', models.PositiveSmallIntegerField(default=1, verbose_name='Nombre de participants prevus')),
                ('delai_decision', models.CharField(choices=[('MAINTENANT', 'Des ouverture des reservations'), ('TROIS_MOIS', 'Dans les 3 mois'), ('PLUS_TARD', 'Plus tard'), ('A_RECONTACTER', 'A recontacter')], default='A_RECONTACTER', max_length=20, verbose_name='Delai de decision')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('consent', models.BooleanField(default=False, verbose_name="Accepte d'etre contacte")),
                ('newsletter_optin', models.BooleanField(default=False, verbose_name='Souhaite recevoir les informations Pulsion Horizon')),
                ('traite', models.BooleanField(db_index=True, default=False, verbose_name='Traite')),
                ('source', models.CharField(blank=True, default='pre_programme_2027', max_length=120, verbose_name='Source')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User agent')),
            ],
            options={
                'verbose_name': 'Interesse pre programme 2027',
                'verbose_name_plural': 'Interesses pre programme 2027',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddField(
            model_name='circuit',
            name='itineraire_active',
            field=models.BooleanField(default=False, help_text='Active le module carte / Street View / jour par jour sur la page détail.', verbose_name='Afficher la carte interactive'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='itineraire_embed_url',
            field=models.URLField(blank=True, help_text="URL iframe optionnelle, utile en secours si la clé Google Maps JS n'est pas configurée.", max_length=900, verbose_name="URL d'intégration Google Maps"),
        ),
        migrations.AddField(
            model_name='circuit',
            name='itineraire_google_maps_url',
            field=models.URLField(blank=True, help_text="Lien public optionnel pour ouvrir l'itinéraire complet dans Google Maps.", max_length=700, verbose_name='Lien Google Maps / My Maps'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='itineraire_points',
            field=models.JSONField(blank=True, default=list, help_text='Liste des jours avec coordonnées. Exemple : [{"day":"Jour 1","title":"Las Vegas","points":[{"label":"Las Vegas","lat":36.1699,"lng":-115.1398}]}]', verbose_name='Itinéraire cartographique (JSON)'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='itineraire_street_view_url',
            field=models.URLField(blank=True, help_text='URL iframe optionnelle pour afficher une vue immersive en secours.', max_length=900, verbose_name="URL d'intégration Street View"),
        ),
        migrations.CreateModel(
            name='Programme2027Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('niveau_interet', models.CharField(choices=[('CURIEUX', 'Curieux'), ('INTERESSE', 'Interesse'), ('TRES_INTERESSE', 'Tres interesse'), ('PRET_A_RESERVER', 'Pret a reserver')], db_index=True, default='INTERESSE', max_length=20, verbose_name="Niveau d'interet")),
                ('participants', models.PositiveSmallIntegerField(default=1, verbose_name='Participants pour ce circuit')),
                ('mode_prefere', models.CharField(blank=True, max_length=140, verbose_name='Mode prefere')),
                ('commentaire', models.CharField(blank=True, max_length=500, verbose_name='Precision')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='circuitMoto.programme2027circuit')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='circuitMoto.programme2027interest')),
            ],
            options={
                'verbose_name': 'Selection pre programme 2027',
                'verbose_name_plural': 'Selections pre programme 2027',
                'ordering': ['circuit__ordre', 'circuit__titre'],
            },
        ),
        migrations.AddField(
            model_name='programme2027interest',
            name='circuits',
            field=models.ManyToManyField(related_name='interesses', through='circuitMoto.Programme2027Selection', to='circuitMoto.programme2027circuit', verbose_name='Circuits interesses'),
        ),
        migrations.AddIndex(
            model_name='programme2027circuit',
            index=models.Index(fields=['actif', 'ordre'], name='cm_p27c_act_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='programme2027circuit',
            index=models.Index(fields=['categorie', 'actif'], name='cm_p27c_cat_act_idx'),
        ),
        migrations.AddIndex(
            model_name='programme2027selection',
            index=models.Index(fields=['circuit', 'niveau_interet'], name='cm_p27s_circuit_idx'),
        ),
        migrations.AddIndex(
            model_name='programme2027selection',
            index=models.Index(fields=['demande', 'niveau_interet'], name='cm_p27s_demande_idx'),
        ),
        migrations.AddConstraint(
            model_name='programme2027selection',
            constraint=models.UniqueConstraint(fields=('demande', 'circuit'), name='uniq_programme2027_selection'),
        ),
        migrations.AddIndex(
            model_name='programme2027interest',
            index=models.Index(fields=['email', 'cree_le'], name='cm_p27i_email_idx'),
        ),
        migrations.AddIndex(
            model_name='programme2027interest',
            index=models.Index(fields=['traite', 'cree_le'], name='cm_p27i_traite_idx'),
        ),
        migrations.AddIndex(
            model_name='programme2027interest',
            index=models.Index(fields=['delai_decision', 'cree_le'], name='cm_p27i_decision_idx'),
        ),
    ]
