# Generated by Django 4.2.23 on 2026-03-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0018_sitevisitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitevisitor',
            options={'verbose_name': 'Visiteur du site', 'verbose_name_plural': 'Visiteurs du site'},
        ),
        migrations.AddField(
            model_name='sitevisitor',
            name='path',
            field=models.CharField(blank=True, default='/', max_length=255, verbose_name='Page visitée'),
        ),
        migrations.AlterField(
            model_name='sitevisitor',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='sitevisitor',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Clé de session'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='sitevisitor',
            index=models.Index(fields=['created_at'], name='circuitMoto_created_0bf016_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisitor',
            index=models.Index(fields=['session_key'], name='circuitMoto_session_f036fb_idx'),
        ),
    ]
