# Generated by Django 4.2.23 on 2026-03-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0019_alter_sitevisitor_options_sitevisitor_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='montant_options_ajoutees',
            field=models.PositiveIntegerField(default=0, verbose_name='Montant options ajoutées après modification'),
        ),
    ]
