# Generated by Django 4.2.23 on 2026-03-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitMoto', '0020_inscription_montant_options_ajoutees'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='paiement_options_recu',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
