# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circuitMoto", "0024_baladejour_slug_lien"),
    ]

    operations = [
        migrations.AddField(
            model_name="circuit",
            name="itineraire_active",
            field=models.BooleanField(
                default=False,
                help_text="Active le module carte / Street View / jour par jour sur la page détail.",
                verbose_name="Afficher la carte interactive",
            ),
        ),
        migrations.AddField(
            model_name="circuit",
            name="itineraire_points",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Liste des jours avec coordonnées. Exemple : "
                    "[{\"day\":\"Jour 1\",\"title\":\"Las Vegas\",\"points\":[{\"label\":\"Las Vegas\",\"lat\":36.1699,\"lng\":-115.1398}]}]"
                ),
                verbose_name="Itinéraire cartographique (JSON)",
            ),
        ),
        migrations.AddField(
            model_name="circuit",
            name="itineraire_google_maps_url",
            field=models.URLField(
                blank=True,
                help_text="Lien public optionnel pour ouvrir l'itinéraire complet dans Google Maps.",
                max_length=700,
                verbose_name="Lien Google Maps / My Maps",
            ),
        ),
        migrations.AddField(
            model_name="circuit",
            name="itineraire_embed_url",
            field=models.URLField(
                blank=True,
                help_text="URL iframe optionnelle, utile en secours si la clé Google Maps JS n'est pas configurée.",
                max_length=900,
                verbose_name="URL d'intégration Google Maps",
            ),
        ),
        migrations.AddField(
            model_name="circuit",
            name="itineraire_street_view_url",
            field=models.URLField(
                blank=True,
                help_text="URL iframe optionnelle pour afficher une vue immersive en secours.",
                max_length=900,
                verbose_name="URL d'intégration Street View",
            ),
        ),
    ]
