# Generated manually for the Pre Programme 2027 feature.

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


PROGRAMME_2027_CIRCUITS = [
    {
        "titre": "Laos",
        "slug": "laos-fevrier-2027",
        "mois": "Fevrier",
        "duree": "14 jours",
        "formule": "Moto ou 4x4",
        "categorie": "GRAND_VOYAGE",
        "ordre": 10,
    },
    {
        "titre": "Vietnam",
        "slug": "vietnam-fevrier-2027",
        "mois": "Fevrier",
        "duree": "14 jours",
        "formule": "Moto ou 4x4",
        "categorie": "GRAND_VOYAGE",
        "ordre": 20,
    },
    {
        "titre": "Sud Maroc - moto loc",
        "slug": "sud-maroc-moto-loc-mars-2027",
        "mois": "Mars",
        "duree": "10 jours",
        "formule": "Moto de location",
        "categorie": "RAID",
        "ordre": 30,
    },
    {
        "titre": "Senegal",
        "slug": "senegal-mars-2027",
        "mois": "Mars",
        "duree": "8 ou 12 jours",
        "formule": "Moto ou 4x4",
        "categorie": "GRAND_VOYAGE",
        "ordre": 40,
    },
    {
        "titre": "USA",
        "slug": "usa-avril-2027",
        "mois": "Avril",
        "duree": "12 ou 17 jours",
        "formule": "Harley ou Mustang",
        "categorie": "GRAND_VOYAGE",
        "ordre": 50,
    },
    {
        "titre": "Foret Noire",
        "slug": "foret-noire-mai-2027",
        "mois": "Mai",
        "duree": "4 ou 5 jours",
        "formule": "Moto",
        "categorie": "EUROPE",
        "ordre": 60,
    },
    {
        "titre": "Sardaigne",
        "slug": "sardaigne-mai-2027",
        "mois": "Mai",
        "duree": "11 ou 13 jours",
        "formule": "Moto",
        "categorie": "EUROPE",
        "ordre": 70,
    },
    {
        "titre": "Morvan",
        "slug": "morvan-mai-2027",
        "mois": "Mai",
        "duree": "5 ou 6 jours",
        "formule": "Moto",
        "categorie": "FRANCE_BELGIQUE",
        "ordre": 80,
    },
    {
        "titre": "Corse I",
        "slug": "corse-i-mai-2027",
        "mois": "Mai",
        "duree": "11 ou 13 jours",
        "formule": "Moto",
        "categorie": "EUROPE",
        "ordre": 90,
    },
    {
        "titre": "Pyrenees",
        "slug": "pyrenees-mai-2027",
        "mois": "Mai",
        "duree": "9 ou 11 jours",
        "formule": "Moto",
        "categorie": "FRANCE_BELGIQUE",
        "ordre": 100,
    },
    {
        "titre": "Toscane",
        "slug": "toscane-juin-2027",
        "mois": "Juin",
        "duree": "7 ou 9 jours",
        "formule": "Moto",
        "categorie": "EUROPE",
        "ordre": 110,
    },
    {
        "titre": "Vosges",
        "slug": "vosges-juin-2027",
        "mois": "Juin",
        "duree": "3 ou 4 jours",
        "formule": "Moto",
        "categorie": "FRANCE_BELGIQUE",
        "ordre": 120,
    },
    {
        "titre": "Corse II",
        "slug": "corse-ii-juin-2027",
        "mois": "Juin",
        "duree": "11 ou 13 jours",
        "formule": "Moto",
        "categorie": "EUROPE",
        "ordre": 130,
    },
    {
        "titre": "Dolomites I",
        "slug": "dolomites-i-juin-2027",
        "mois": "Juin",
        "duree": "8 ou 9 jours",
        "formule": "Moto",
        "categorie": "EUROPE",
        "ordre": 140,
    },
    {
        "titre": "Alsace I",
        "slug": "alsace-i-juin-2027",
        "mois": "Juin",
        "duree": "3 ou 5 jours",
        "formule": "Moto",
        "categorie": "FRANCE_BELGIQUE",
        "lien_reference": "https://pulsionhorizon.com/alsace",
        "ordre": 150,
    },
    {
        "titre": "Corse autrement",
        "slug": "corse-autrement-juin-2027",
        "mois": "Juin",
        "duree": "11 ou 13 jours",
        "formule": "Moto",
        "categorie": "EUROPE",
        "ordre": 160,
    },
    {
        "titre": "Cote d'Opale - Normandie",
        "slug": "cote-opale-normandie-juin-2027",
        "mois": "Juin",
        "duree": "4 jours",
        "formule": "Moto",
        "categorie": "FRANCE_BELGIQUE",
        "ordre": 170,
    },
    {
        "titre": "Normandie - Bretagne",
        "slug": "normandie-bretagne-juin-2027",
        "mois": "Juin",
        "duree": "6 ou 7 jours",
        "formule": "Moto",
        "categorie": "FRANCE_BELGIQUE",
        "ordre": 180,
    },
    {
        "titre": "Cote d'Opale - Normandie - Bretagne",
        "slug": "cote-opale-normandie-bretagne-juin-2027",
        "mois": "Juin",
        "duree": "8 ou 9 jours",
        "formule": "Moto",
        "categorie": "FRANCE_BELGIQUE",
        "ordre": 190,
    },
    {
        "titre": "Ecosse",
        "slug": "ecosse-juin-2027",
        "mois": "Juin",
        "duree": "9 jours",
        "formule": "Moto",
        "categorie": "EUROPE",
        "ordre": 200,
    },
    {
        "titre": "Jura",
        "slug": "jura-juin-2027",
        "mois": "Juin",
        "duree": "5 ou 6 jours",
        "formule": "Moto",
        "categorie": "FRANCE_BELGIQUE",
        "ordre": 210,
    },
    {
        "titre": "Corse III",
        "slug": "corse-iii-septembre-2027",
        "mois": "Septembre",
        "duree": "11 ou 13 jours",
        "formule": "Moto",
        "categorie": "EUROPE",
        "ordre": 220,
    },
    {
        "titre": "Corse IV",
        "slug": "corse-iv-septembre-2027",
        "mois": "Septembre",
        "duree": "11 ou 13 jours",
        "formule": "Moto",
        "categorie": "EUROPE",
        "ordre": 230,
    },
    {
        "titre": "Alpes du sud",
        "slug": "alpes-du-sud-septembre-2027",
        "mois": "Septembre",
        "duree": "9 ou 10 jours",
        "formule": "Moto",
        "categorie": "FRANCE_BELGIQUE",
        "ordre": 240,
    },
    {
        "titre": "Croatie",
        "slug": "croatie-septembre-2027",
        "mois": "Septembre",
        "duree": "14 ou 15 jours",
        "formule": "Moto",
        "categorie": "EUROPE",
        "ordre": 250,
    },
    {
        "titre": "Albanie Grece",
        "slug": "albanie-grece-septembre-2027",
        "mois": "Septembre",
        "duree": "14 ou 15 jours",
        "formule": "Moto",
        "categorie": "EUROPE",
        "ordre": 260,
    },
    {
        "titre": "Champagne",
        "slug": "champagne-septembre-2027",
        "mois": "Septembre",
        "duree": "3 ou 4 jours",
        "formule": "Moto",
        "categorie": "FRANCE_BELGIQUE",
        "ordre": 270,
    },
    {
        "titre": "Dolomites II",
        "slug": "dolomites-ii-septembre-2027",
        "mois": "Septembre",
        "duree": "8 ou 9 jours",
        "formule": "Moto",
        "categorie": "EUROPE",
        "ordre": 280,
    },
    {
        "titre": "Alsace II",
        "slug": "alsace-ii-septembre-2027",
        "mois": "Septembre",
        "duree": "3 ou 5 jours",
        "formule": "Moto",
        "categorie": "FRANCE_BELGIQUE",
        "lien_reference": "https://pulsionhorizon.com/alsace",
        "ordre": 290,
    },
    {
        "titre": "Usine Guzzi",
        "slug": "usine-guzzi-septembre-2027",
        "mois": "Septembre",
        "duree": "5 jours",
        "formule": "Moto",
        "categorie": "EUROPE",
        "ordre": 300,
    },
    {
        "titre": "Namibie",
        "slug": "namibie-octobre-2027",
        "mois": "Octobre",
        "duree": "14 jours",
        "formule": "Moto ou 4x4",
        "categorie": "GRAND_VOYAGE",
        "ordre": 310,
    },
    {
        "titre": "Raid Bxl/Dakar",
        "slug": "raid-bxl-dakar-octobre-2027",
        "mois": "Octobre",
        "duree": "24 jours",
        "formule": "100% route ou mixte route et piste",
        "categorie": "RAID",
        "ordre": 320,
    },
    {
        "titre": "Raid sud Maroc",
        "slug": "raid-sud-maroc-octobre-2027",
        "mois": "Octobre",
        "duree": "16 jours",
        "formule": "Route ou piste",
        "categorie": "RAID",
        "lien_reference": "https://pulsionhorizon.com/raid-sud-maroc-2026",
        "ordre": 330,
    },
    {
        "titre": "Sud Maroc - moto loc",
        "slug": "sud-maroc-moto-loc-octobre-2027",
        "mois": "Octobre",
        "duree": "10 jours",
        "formule": "Moto de location",
        "categorie": "RAID",
        "ordre": 340,
    },
    {
        "titre": "Senegal",
        "slug": "senegal-novembre-2027",
        "mois": "Novembre",
        "duree": "8 ou 12 jours",
        "formule": "Moto ou 4x4",
        "categorie": "GRAND_VOYAGE",
        "ordre": 350,
    },
]

def seed_programme_2027(apps, schema_editor):
    Circuit = apps.get_model("circuitMoto", "Programme2027Circuit")
    for item in PROGRAMME_2027_CIRCUITS:
        defaults = item.copy()
        slug = defaults.pop("slug")
        Circuit.objects.update_or_create(slug=slug, defaults=defaults)


def unseed_programme_2027(apps, schema_editor):
    Circuit = apps.get_model("circuitMoto", "Programme2027Circuit")
    Circuit.objects.filter(slug__in=[item["slug"] for item in PROGRAMME_2027_CIRCUITS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("circuitMoto", "0025_circuit_itineraire_maps"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programme2027Circuit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cree_le", models.DateTimeField(auto_now_add=True, editable=False)),
                ("modifie_le", models.DateTimeField(auto_now=True, editable=False)),
                ("titre", models.CharField(max_length=180, verbose_name="Circuit")),
                ("slug", models.SlugField(max_length=190, unique=True, verbose_name="Slug")),
                ("mois", models.CharField(max_length=80, verbose_name="Mois / periode")),
                ("duree", models.CharField(max_length=80, verbose_name="Duree")),
                ("formule", models.CharField(blank=True, max_length=180, verbose_name="Formule")),
                ("categorie", models.CharField(choices=[("GRAND_VOYAGE", "Grand voyage"), ("EUROPE", "Europe"), ("FRANCE_BELGIQUE", "France / Belgique"), ("RAID", "Raid / aventure")], db_index=True, default="EUROPE", max_length=24, verbose_name="Categorie")),
                ("lien_reference", models.URLField(blank=True, max_length=700, verbose_name="Lien reference")),
                ("note", models.TextField(blank=True, verbose_name="Note interne")),
                ("ordre", models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage")),
                ("actif", models.BooleanField(db_index=True, default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Circuit pre programme 2027",
                "verbose_name_plural": "Circuits pre programme 2027",
                "ordering": ["ordre", "titre"],
            },
        ),
        migrations.CreateModel(
            name="Programme2027Interest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cree_le", models.DateTimeField(auto_now_add=True, editable=False)),
                ("modifie_le", models.DateTimeField(auto_now=True, editable=False)),
                ("prenom", models.CharField(max_length=80, verbose_name="Prenom")),
                ("nom", models.CharField(max_length=80, verbose_name="Nom")),
                ("email", models.EmailField(db_index=True, max_length=254, verbose_name="Email")),
                ("telephone", models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message="Numéro de téléphone invalide.", regex="^[0-9+\\s\\-().]{6,20}$")], verbose_name="Telephone")),
                ("adresse", models.CharField(blank=True, max_length=255, verbose_name="Adresse")),
                ("code_postal", models.CharField(blank=True, max_length=20, verbose_name="Code postal")),
                ("localite", models.CharField(blank=True, max_length=80, verbose_name="Localite")),
                ("pays", models.CharField(blank=True, max_length=80, verbose_name="Pays")),
                ("profil", models.CharField(blank=True, max_length=120, verbose_name="Profil voyageur")),
                ("vehicule", models.CharField(blank=True, max_length=160, verbose_name="Vehicule / preference")),
                ("participants_previsionnels", models.PositiveSmallIntegerField(default=1, verbose_name="Nombre de participants prevus")),
                ("delai_decision", models.CharField(choices=[("MAINTENANT", "Des ouverture des reservations"), ("TROIS_MOIS", "Dans les 3 mois"), ("PLUS_TARD", "Plus tard"), ("A_RECONTACTER", "A recontacter")], default="A_RECONTACTER", max_length=20, verbose_name="Delai de decision")),
                ("commentaire", models.TextField(blank=True, verbose_name="Commentaire")),
                ("consent", models.BooleanField(default=False, verbose_name="Accepte d'etre contacte")),
                ("newsletter_optin", models.BooleanField(default=False, verbose_name="Souhaite recevoir les informations Pulsion Horizon")),
                ("traite", models.BooleanField(db_index=True, default=False, verbose_name="Traite")),
                ("source", models.CharField(blank=True, default="pre_programme_2027", max_length=120, verbose_name="Source")),
                ("ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP")),
                ("user_agent", models.CharField(blank=True, max_length=255, verbose_name="User agent")),
            ],
            options={
                "verbose_name": "Interesse pre programme 2027",
                "verbose_name_plural": "Interesses pre programme 2027",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="Programme2027Selection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cree_le", models.DateTimeField(auto_now_add=True, editable=False)),
                ("modifie_le", models.DateTimeField(auto_now=True, editable=False)),
                ("niveau_interet", models.CharField(choices=[("CURIEUX", "Curieux"), ("INTERESSE", "Interesse"), ("TRES_INTERESSE", "Tres interesse"), ("PRET_A_RESERVER", "Pret a reserver")], db_index=True, default="INTERESSE", max_length=20, verbose_name="Niveau d'interet")),
                ("participants", models.PositiveSmallIntegerField(default=1, verbose_name="Participants pour ce circuit")),
                ("mode_prefere", models.CharField(blank=True, max_length=140, verbose_name="Mode prefere")),
                ("commentaire", models.CharField(blank=True, max_length=500, verbose_name="Precision")),
                ("circuit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="selections", to="circuitMoto.programme2027circuit")),
                ("demande", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="selections", to="circuitMoto.programme2027interest")),
            ],
            options={
                "verbose_name": "Selection pre programme 2027",
                "verbose_name_plural": "Selections pre programme 2027",
                "ordering": ["circuit__ordre", "circuit__titre"],
            },
        ),
        migrations.AddField(
            model_name="programme2027interest",
            name="circuits",
            field=models.ManyToManyField(related_name="interesses", through="circuitMoto.Programme2027Selection", to="circuitMoto.programme2027circuit", verbose_name="Circuits interesses"),
        ),
        migrations.AddIndex(
            model_name="programme2027circuit",
            index=models.Index(fields=["actif", "ordre"], name="cm_p27c_act_ord_idx"),
        ),
        migrations.AddIndex(
            model_name="programme2027circuit",
            index=models.Index(fields=["categorie", "actif"], name="cm_p27c_cat_act_idx"),
        ),
        migrations.AddIndex(
            model_name="programme2027interest",
            index=models.Index(fields=["email", "cree_le"], name="cm_p27i_email_idx"),
        ),
        migrations.AddIndex(
            model_name="programme2027interest",
            index=models.Index(fields=["traite", "cree_le"], name="cm_p27i_traite_idx"),
        ),
        migrations.AddIndex(
            model_name="programme2027interest",
            index=models.Index(fields=["delai_decision", "cree_le"], name="cm_p27i_decision_idx"),
        ),
        migrations.AddIndex(
            model_name="programme2027selection",
            index=models.Index(fields=["circuit", "niveau_interet"], name="cm_p27s_circuit_idx"),
        ),
        migrations.AddIndex(
            model_name="programme2027selection",
            index=models.Index(fields=["demande", "niveau_interet"], name="cm_p27s_demande_idx"),
        ),
        migrations.AddConstraint(
            model_name="programme2027selection",
            constraint=models.UniqueConstraint(fields=("demande", "circuit"), name="uniq_programme2027_selection"),
        ),
        migrations.RunPython(seed_programme_2027, unseed_programme_2027),
    ]
