"""
Django settings for circuitprojet project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
# circuitprojet/settings.py
from pathlib import Path
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wbk&4(e9l17&2z%%&c7bj!h$dj0%f4lbl$12h8^(=)hy_#x*#*'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

#ALLOWED_HOSTS = []

DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = ["84.247.132.41", "pulsion-inscription.com", "www.pulsion-inscription.com", "localhost", "127.0.0.1"]  # <- mets l'IP publique du serveur
CSRF_TRUSTED_ORIGINS = [
    "https://pulsion-inscription.com",
    "https://www.pulsion-inscription.com",


    "http://84.247.132.41:8001",
    "http://localhost:8001",
    "http://127.0.0.1:8001",
]


# Application definition

INSTALLED_APPS = [
    "modeltranslation",              # doit être AVANT l'app
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "django.contrib.sitemaps",

    # humanize est une dépendance de formtools, mais on peut aussi l'utiliser dans nos templates
    "django.contrib.humanize",

    "circuitMoto.apps.CircuitMotoConfig",   # ← au lieu de "circuitMoto"
    "formtools",
]

MODELTRANSLATION_DEFAULT_LANGUAGE = "fr"
MODELTRANSLATION_ENABLE_FALLBACKS = True
MODELTRANSLATION_FALLBACK_LANGUAGES = ("fr",)


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",   # <= ici
    "django.middleware.common.CommonMiddleware",
    "circuitMoto.middleware.NoCacheHtmlMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "circuitMoto.middleware.ForcePasswordChangeMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'circuitprojet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
		'circuitMoto.context_processors.site_prefs',
            ],
        },
    },
]

WSGI_APPLICATION = 'circuitprojet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'circuit',
        'USER': 'postgres',
        'PASSWORD': 'P@sser@12',
        'HOST': 'localhost',   
        'PORT': '5432',        
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

    # 👇 notre validateur
    {
        'NAME': 'circuitMoto.validators.PreventPasswordReuseValidator'
    },

]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Langues proposées à l’utilisateur
LANGUAGES = [
    ("fr", "Français"),
    ("en", "English"),
]

# Où stocker les .po/.mo
LOCALE_PATHS = [BASE_DIR / "locale"]

# Cookie de langue (optionnel mais propre)
LANGUAGE_COOKIE_NAME = "django_language"
LANGUAGE_COOKIE_AGE = 60 * 60 * 24 * 365  # 1 an
LANGUAGE_COOKIE_SAMESITE = "Lax"


# Langues proposées à l’utilisateur
LANGUAGES = [
    ("fr", "Français"),
    ("en", "English"),
]

# Où stocker les .po/.mo
LOCALE_PATHS = [BASE_DIR / "locale"]

# Cookie de langue (optionnel mais propre)
LANGUAGE_COOKIE_NAME = "django_language"
LANGUAGE_COOKIE_AGE = 60 * 60 * 24 * 365  # 1 an
LANGUAGE_COOKIE_SAMESITE = "Lax"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

#STATIC_URL = 'static/'

#MEDIA_URL = '/images/'

#STATICFILES_DIRS = [
#    BASE_DIR / 'static'
#]

#MEDIA_ROOT = BASE_DIR / 'static/images'


# STATIC_URL = 'static/'

# MEDIA_URL = '/images/'

# STATICFILES_DIRS = [
#    BASE_DIR / 'static'
#]

# STATIC_ROOT = BASE_DIR / "staticfiles"

#MEDIA_ROOT = BASE_DIR / 'static/images'

# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'   # => /home/circuitMoto/media

# --- STATIC ---
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATIC_VERSION = os.environ.get("STATIC_VERSION", "")
STATIC_VERSION_QUERY = os.environ.get("STATIC_VERSION_QUERY", "True").lower() in {"1", "true", "yes", "on"}
STATIC_VERSION_PARAM = os.environ.get("STATIC_VERSION_PARAM", "v")
STATIC_VERSION_EXTENSIONS = (
    ".css", ".js", ".mjs", ".json", ".map",
    ".svg", ".png", ".jpg", ".jpeg", ".webp", ".gif", ".ico",
    ".woff", ".woff2",
)

# --- MEDIA ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Permissions conseillées (évite des surprises)
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# (Optionnel) Seuils mémoire d'upload
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024      # 10 Mo en mémoire
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024       # 2 Mo en mémoire

# Cache-busting automatique : collectstatic génère des noms avec hash de contenu.
# Exemple : circuitMoto/js/base.js -> circuitMoto/js/base.4f3a1c2b9d8e.js.
# Après chaque déploiement, exécuter : python manage.py collectstatic --noinput
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        # OPTIONS facultatif : FileSystemStorage utilise MEDIA_ROOT/MEDIA_URL par défaut
        # "OPTIONS": {"location": MEDIA_ROOT},
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "bayesalioudiawtech@gmail.com"
# EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_APP_PASSWORD")   # <— variable d’env.

EMAIL_HOST_PASSWORD = "ulxs yeqw ngxl eqde"

DEFAULT_FROM_EMAIL = "Pulsion Horizon <bayesalioudiawtech@gmail.com>"
SITE_URL = os.environ.get("SITE_URL", "http://127.0.0.1:8000")
GOOGLE_MAPS_API_KEY = os.environ.get("GOOGLE_MAPS_API_KEY", "").strip()
PASSWORD_RESET_TIMEOUT = 60 * 60 * 2
EMAIL_TIMEOUT = 15
NOTIFY_ADMIN_EMAIL = os.environ.get("NOTIFY_ADMIN_EMAIL", "bayesalioudiawtech@gmail.com")
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp-relay.brevo.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True

# EMAIL_HOST_USER = os.environ.get("BREVO_SMTP_LOGIN")
# EMAIL_HOST_PASSWORD = os.environ.get("BREVO_SMTP_KEY")

# DEFAULT_FROM_EMAIL = "Pulsion Horizon <info@pulsion-horizon.com>"
# SERVER_EMAIL = DEFAULT_FROM_EMAIL

# SITE_URL = os.environ.get("SITE_URL", "https://pulsion-inscription.com")
# PASSWORD_RESET_TIMEOUT = 60 * 60 * 2
# EMAIL_TIMEOUT = 15
# NOTIFY_ADMIN_EMAIL = os.environ.get("NOTIFY_ADMIN_EMAIL", "info@pulsion-horizon.com")

CSRF_FAILURE_VIEW = "circuitMoto.errors.csrf_failure"


# =========================
# NEWSLETTER / EMAILING DE MASSE
# =========================
NEWSLETTER_ENABLED = True

# Nombre max d'emails acceptés dans un envoi manuel
NEWSLETTER_MAX_RECIPIENTS_PER_SEND = 1500

# Taille d'un lot d'envoi SMTP
NEWSLETTER_BATCH_SIZE = 50

# Pause entre lots (en secondes)
NEWSLETTER_SLEEP_SECONDS = 1

# Taille max cumulée des pièces jointes
NEWSLETTER_MAX_ATTACHMENT_BYTES = 25 * 1024 * 1024  # 25 Mo

# Si True, l'ancien module emailing par circuit peut être masqué
NEWSLETTER_HIDE_OLD_EMAILING = True


# ——— PAUSE TEMPORAIRE DES EMAILS ———
# Coupe tous les emails vers les utilisateurs (pilote & passager)
EMAILS_PAUSE_TOUS_UTILISATEURS = False

# Coupe uniquement les emails destinés au pilote (ce que tu demandes)
EMAILS_PAUSE_PILOTE = False

# (Optionnel) Coupe ceux du passager aussi si besoin
EMAILS_PAUSE_PASSAGER = False
